namespace Mail2SNMP.Models.Enums;

/// <summary>
/// Identifies which field of an incoming email a rule condition evaluates.
/// </summary>
public enum RuleFieldType
{
    /// <summary>Match against the email subject line.</summary>
    Subject,

    /// <summary>Match against the sender (From) address.</summary>
    From,

    /// <summary>Match against the recipient (To) address.</summary>
    To,

    /// <summary>Match against the email body content.</summary>
    Body,

    /// <summary>Match against a specific email header value.</summary>
    Header
}

/// <summary>
/// Defines how a rule condition compares the field value to the expected pattern.
/// </summary>
public enum RuleMatchType
{
    /// <summary>The field value contains the specified text.</summary>
    Contains,

    /// <summary>The field value exactly equals the specified text.</summary>
    Equals,

    /// <summary>The field value matches the specified regular expression.</summary>
    Regex,

    /// <summary>The field value starts with the specified text.</summary>
    StartsWith,

    /// <summary>The field value ends with the specified text.</summary>
    EndsWith
}

/// <summary>
/// Indicates the severity level assigned to an event generated by a matched rule.
/// </summary>
public enum Severity
{
    /// <summary>Informational event that requires no immediate action.</summary>
    Information,

    /// <summary>Warning event that may require attention.</summary>
    Warning,

    /// <summary>Error event indicating a significant problem.</summary>
    Error,

    /// <summary>Critical event requiring immediate attention.</summary>
    Critical
}
