using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Mail2SNMP.Models.Entities;

/// <summary>
/// A polling job that links a mailbox to a parsing rule and one or more notification targets.
/// Targets are assigned per-job via the JobSnmpTargets and JobWebhookTargets join tables.
/// </summary>
public class Job
{
    /// <summary>Surrogate primary key. Database-generated identity; zero on a not-yet-persisted instance.</summary>
    public int Id { get; set; }

    /// <summary>Operator-facing display name for the job. Required and must be non-empty.</summary>
    [Required(ErrorMessage = "Name is required.")]
    public string Name { get; set; } = string.Empty;

    /// <summary>
    /// FK to the <see cref="Mailbox"/> this job polls. The <c>Range</c> attribute rejects 0,
    /// which is the "no selection" sentinel from the UI dropdown.
    /// </summary>
    [Range(1, int.MaxValue, ErrorMessage = "Please select a mailbox.")]
    public int MailboxId { get; set; }

    /// <summary>Navigation property for the mailbox referenced by <see cref="MailboxId"/>.</summary>
    public Mailbox Mailbox { get; set; } = null!;

    /// <summary>
    /// FK to the <see cref="Rule"/> applied to incoming mail for this job. The <c>Range</c>
    /// attribute rejects 0, the "no selection" sentinel from the UI dropdown.
    /// </summary>
    [Range(1, int.MaxValue, ErrorMessage = "Please select a rule.")]
    public int RuleId { get; set; }

    /// <summary>Navigation property for the rule referenced by <see cref="RuleId"/>.</summary>
    public Rule Rule { get; set; } = null!;

    /// <summary>
    /// Backward-compatible computed property: derives channel names from the assigned targets.
    /// Not mapped to the database — the join tables are the source of truth.
    /// </summary>
    [NotMapped]
    public string Channels
    {
        get
        {
            var parts = new List<string>();
            if (JobSnmpTargets.Count > 0) parts.Add("snmp");
            if (JobWebhookTargets.Count > 0) parts.Add("webhook");
            return parts.Count > 0 ? string.Join(",", parts) : "none";
        }
    }

    /// <summary>
    /// Optional override template for the SNMP trap payload. When <c>null</c> the system default
    /// trap template is used. Plaintext; not encrypted.
    /// </summary>
    public string? TrapTemplate { get; set; }

    /// <summary>
    /// Optional override template for the webhook JSON payload. When <c>null</c> the system default
    /// webhook template is used. Plaintext; not encrypted.
    /// </summary>
    public string? WebhookTemplate { get; set; }

    /// <summary>
    /// Optional mapping that binds parsed event fields to SNMP OIDs (e.g. JSON or key/value pairs).
    /// <c>null</c> falls back to the default OID mapping for the target.
    /// </summary>
    public string? OidMapping { get; set; }

    /// <summary>
    /// Per-job rate limit: maximum number of events this job may emit within a rolling one-hour window.
    /// Events beyond this cap are throttled. Range 1–10,000; defaults to 50.
    /// </summary>
    [Range(1, 10000, ErrorMessage = "Max events per hour must be between 1 and 10,000.")]
    public int MaxEventsPerHour { get; set; } = 50;

    /// <summary>
    /// Upper bound on the number of concurrently active (un-resolved) events for this job, guarding
    /// against event-storm flooding. Range 1–100,000; defaults to 200.
    /// </summary>
    [Range(1, 100000, ErrorMessage = "Max active events must be between 1 and 100,000.")]
    public int MaxActiveEvents { get; set; } = 200;

    /// <summary>
    /// Deduplication window in <b>minutes</b>. Duplicate matches within this window increment an
    /// existing event's hit count instead of creating a new event. A value of 0 disables
    /// deduplication. Range 0–1440 (24 hours); defaults to 30.
    /// </summary>
    [Range(0, 1440, ErrorMessage = "Dedup window must be between 0 and 1440 minutes.")]
    public int DedupWindowMinutes { get; set; } = 30;

    /// <summary>Whether the job participates in polling. Inactive jobs are skipped by the worker. Defaults to <c>true</c>.</summary>
    public bool IsActive { get; set; } = true;

    /// <summary>UTC timestamp recorded when the job was created. Defaults to the current UTC time.</summary>
    public DateTime CreatedUtc { get; set; } = DateTime.UtcNow;

    /// <summary>
    /// EF Core optimistic-concurrency token. Updated by the database on each row change; a stale
    /// value causes a concurrency conflict on save rather than a lost update.
    /// </summary>
    public byte[] RowVersion { get; set; } = Array.Empty<byte>();

    /// <summary>Schedules that constrain when this job is allowed to poll (e.g. business-hours windows). Lazy-loaded navigation collection.</summary>
    public ICollection<Schedule> Schedules { get; set; } = new List<Schedule>();

    /// <summary>Events generated by this job. Lazy-loaded navigation collection.</summary>
    public ICollection<Event> Events { get; set; } = new List<Event>();

    // Per-job target assignments (many-to-many via join tables)

    /// <summary>
    /// Join-table rows assigning <see cref="SnmpTarget"/>s to this job (many-to-many).
    /// This collection, not <see cref="Channels"/>, is the source of truth for SNMP delivery.
    /// </summary>
    public ICollection<JobSnmpTarget> JobSnmpTargets { get; set; } = new List<JobSnmpTarget>();

    /// <summary>
    /// Join-table rows assigning <see cref="WebhookTarget"/>s to this job (many-to-many).
    /// This collection, not <see cref="Channels"/>, is the source of truth for webhook delivery.
    /// </summary>
    public ICollection<JobWebhookTarget> JobWebhookTargets { get; set; } = new List<JobWebhookTarget>();
}
