// <auto-generated />
using System;
using Mail2SNMP.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Mail2SNMP.Infrastructure.Data.Migrations
{
    [DbContext(typeof(Mail2SnmpDbContext))]
    [Migration("20260612090000_AddSnmpDeadLetter")]
    partial class AddSnmpDeadLetter
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.25");

            modelBuilder.Entity("Mail2SNMP.Models.Entities.ApiKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<DateTime>("CreatedUtc");

                    b.Property<DateTime?>("ExpiresUtc");

                    b.Property<bool>("IsActive");

                    b.Property<string>("KeyHash")
                        .IsRequired()
                        .HasMaxLength(128);

                    b.Property<string>("KeyPrefix")
                        .IsRequired()
                        .HasMaxLength(16);

                    b.Property<DateTime?>("LastUsedUtc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<string>("Scopes")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.HasKey("Id");

                    b.HasIndex("KeyHash")
                        .IsUnique();

                    b.HasIndex("KeyPrefix");

                    b.ToTable("ApiKeys");
                });

            modelBuilder.Entity("Mail2SNMP.Models.Entities.AppUser", b =>
                {
                    b.Property<string>("Id");

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<DateTime>("CreatedUtc");

                    b.Property<string>("DisplayName")
                        .IsRequired();

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<bool>("IsActive");

                    b.Property<DateTime?>("LastLoginUtc");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Mail2SNMP.Models.Entities.AuditEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<string>("ActorId")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<int>("ActorType");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(100);

                    b.Property<string>("Details")
                        .HasMaxLength(4096);

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50);

                    b.Property<int>("Result");

                    b.Property<int>("SchemaVersion");

                    b.Property<string>("TargetId");

                    b.Property<string>("TargetType");

                    b.Property<DateTime>("TimestampUtc");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500);

                    b.HasKey("Id");

                    b.HasIndex("Action");

                    b.HasIndex("TimestampUtc");

                    b.ToTable("AuditEvents");
                });

            modelBuilder.Entity("Mail2SNMP.Models.Entities.AuthTicket", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(200);

                    b.Property<DateTime?>("ExpiresUtc");

                    b.Property<DateTime?>("LastActivity");

                    b.Property<byte[]>("Value")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("ExpiresUtc");

                    b.ToTable("AuthTickets");
                });

            modelBuilder.Entity("Mail2SNMP.Models.Entities.DeadLetterEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AttemptCount");

                    b.Property<DateTime>("CreatedUtc");

                    b.Property<long>("EventId");

                    b.Property<string>("LastError");

                    b.Property<string>("LockedByInstanceId")
                        .HasMaxLength(100);

                    b.Property<DateTime?>("LockedUntilUtc");

                    b.Property<DateTime?>("NextRetryUtc");

                    b.Property<string>("PayloadJson")
                        .IsRequired();

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<int?>("SnmpTargetId");

                    b.Property<int>("Status");

                    b.Property<int?>("WebhookTargetId");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("SnmpTargetId");

                    b.HasIndex("WebhookTargetId");

                    b.HasIndex("Status", "LockedUntilUtc");

                    b.ToTable("DeadLetterEntries");
                });

            modelBuilder.Entity("Mail2SNMP.Models.Entities.Event", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AcknowledgedBy");

                    b.Property<DateTime?>("AcknowledgedUtc");

                    b.Property<DateTime>("CreatedUtc");

                    b.Property<int>("HitCount");

                    b.Property<int>("JobId");

                    b.Property<DateTime?>("LastStateChangeUtc");

                    b.Property<string>("MailFrom")
                        .HasMaxLength(500);

                    b.Property<string>("MessageId");

                    b.Property<DateTime?>("NotifiedUtc");

                    b.Property<string>("ResolvedBy");

                    b.Property<DateTime?>("ResolvedUtc");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<string>("RuleName");

                    b.Property<int>("Severity");

                    b.Property<int>("State");

                    b.Property<string>("Subject")
                        .HasMaxLength(500);

                    b.HasKey("Id");

                    b.HasIndex("JobId", "State");

                    b.HasIndex("State", "CreatedUtc");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("Mail2SNMP.Models.Entities.EventDedup", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("DedupKeyHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsFixedLength();

                    b.Property<long>("EventId");

                    b.Property<DateTime>("FirstSeenUtc");

                    b.Property<int>("JobId");

                    b.Property<DateTime>("LastSeenUtc");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("JobId");

                    b.HasIndex("LastSeenUtc");

                    b.HasIndex("DedupKeyHash", "JobId")
                        .IsUnique();

                    b.ToTable("EventDedups");
                });

            modelBuilder.Entity("Mail2SNMP.Models.Entities.Job", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedUtc");

                    b.Property<int>("DedupWindowMinutes");

                    b.Property<bool>("IsActive");

                    b.Property<int>("MailboxId");

                    b.Property<int>("MaxActiveEvents");

                    b.Property<int>("MaxEventsPerHour");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<string>("OidMapping");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<int>("RuleId");

                    b.Property<string>("TrapTemplate");

                    b.Property<string>("WebhookTemplate");

                    b.HasKey("Id");

                    b.HasIndex("MailboxId");

                    b.HasIndex("RuleId");

                    b.ToTable("Jobs");
                });

            modelBuilder.Entity("Mail2SNMP.Models.Entities.JobSnmpTarget", b =>
                {
                    b.Property<int>("JobId");

                    b.Property<int>("SnmpTargetId");

                    b.HasKey("JobId", "SnmpTargetId");

                    b.HasIndex("SnmpTargetId");

                    b.ToTable("JobSnmpTargets");
                });

            modelBuilder.Entity("Mail2SNMP.Models.Entities.JobWebhookTarget", b =>
                {
                    b.Property<int>("JobId");

                    b.Property<int>("WebhookTargetId");

                    b.HasKey("JobId", "WebhookTargetId");

                    b.HasIndex("WebhookTargetId");

                    b.ToTable("JobWebhookTargets");
                });

            modelBuilder.Entity("Mail2SNMP.Models.Entities.Mailbox", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedUtc");

                    b.Property<string>("EncryptedPassword")
                        .IsRequired()
                        .HasMaxLength(2000);

                    b.Property<string>("Folder")
                        .IsRequired()
                        .HasMaxLength(500);

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasMaxLength(500);

                    b.Property<bool>("IsActive");

                    b.Property<DateTime?>("LastCheckedUtc");

                    b.Property<string>("LastError");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<int>("Port");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<bool>("UseSsl");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(500);

                    b.HasKey("Id");

                    b.ToTable("Mailboxes");
                });

            modelBuilder.Entity("Mail2SNMP.Models.Entities.MaintenanceWindow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<DateTime>("CreatedUtc");

                    b.Property<DateTime>("EndUtc");

                    b.Property<bool>("IsActive");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<string>("RecurringCron");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(500);

                    b.Property<DateTime>("StartUtc");

                    b.HasKey("Id");

                    b.ToTable("MaintenanceWindows");
                });

            modelBuilder.Entity("Mail2SNMP.Models.Entities.ProcessedMail", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Disposition");

                    b.Property<long?>("EventId");

                    b.Property<string>("From");

                    b.Property<int>("MailboxId");

                    b.Property<string>("MessageId")
                        .IsRequired()
                        .HasMaxLength(1000);

                    b.Property<DateTime>("ProcessedUtc");

                    b.Property<DateTime>("ReceivedUtc");

                    b.Property<string>("Subject");

                    b.HasKey("Id");

                    b.HasIndex("MailboxId");

                    b.HasIndex("ProcessedUtc");

                    b.HasIndex("MessageId", "MailboxId")
                        .IsUnique();

                    b.ToTable("ProcessedMails");
                });

            modelBuilder.Entity("Mail2SNMP.Models.Entities.Rule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedUtc");

                    b.Property<string>("Criteria")
                        .IsRequired()
                        .HasMaxLength(2000);

                    b.Property<int?>("DedupWindowMinutes");

                    b.Property<int>("Field");

                    b.Property<bool>("IsActive");

                    b.Property<int>("MatchType");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<int>("Priority");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<int>("Severity");

                    b.HasKey("Id");

                    b.ToTable("Rules");
                });

            modelBuilder.Entity("Mail2SNMP.Models.Entities.Schedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedUtc");

                    b.Property<int>("IntervalMinutes");

                    b.Property<bool>("IsActive");

                    b.Property<int>("JobId");

                    b.Property<DateTime?>("LastRunUtc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<DateTime?>("NextRunUtc");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate();

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.ToTable("Schedules");
                });

            modelBuilder.Entity("Mail2SNMP.Models.Entities.Setting", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(200);

                    b.Property<DateTime>("UpdatedUtc");

                    b.Property<string>("Value")
                        .HasMaxLength(2000);

                    b.HasKey("Key");

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("Mail2SNMP.Models.Entities.SnmpTarget", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AuthProtocol");

                    b.Property<DateTime>("CreatedUtc");

                    b.Property<string>("EncryptedAuthPassword")
                        .HasMaxLength(2000);

                    b.Property<string>("EncryptedCommunityString")
                        .HasMaxLength(2000);

                    b.Property<string>("EncryptedPrivPassword")
                        .HasMaxLength(2000);

                    b.Property<string>("EngineId")
                        .HasMaxLength(200);

                    b.Property<string>("EnterpriseTrapOid")
                        .HasMaxLength(500);

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasMaxLength(500);

                    b.Property<bool>("IsActive");

                    b.Property<int>("MaxTrapsPerMinute");

                    b.Property<int>("MinSeverity");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<int>("Port");

                    b.Property<int>("PrivProtocol");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<string>("SecurityName")
                        .HasMaxLength(200);

                    b.Property<bool>("SendKeepAlive");

                    b.Property<int>("Version");

                    b.HasKey("Id");

                    b.ToTable("SnmpTargets");
                });

            modelBuilder.Entity("Mail2SNMP.Models.Entities.WebhookTarget", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedUtc");

                    b.Property<string>("EncryptedSecret")
                        .HasMaxLength(2000);

                    b.Property<string>("Headers")
                        .HasMaxLength(4000);

                    b.Property<bool>("IsActive");

                    b.Property<int>("MaxRequestsPerMinute");

                    b.Property<int>("MinSeverity");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<string>("PayloadTemplate")
                        .HasMaxLength(8000);

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2000);

                    b.HasKey("Id");

                    b.ToTable("WebhookTargets");
                });

            modelBuilder.Entity("Mail2SNMP.Models.Entities.WorkerLease", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("InstanceId")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<DateTime>("LastHeartbeatUtc");

                    b.Property<string>("LicenseEdition")
                        .IsRequired();

                    b.Property<string>("MachineName")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<DateTime>("StartedUtc");

                    b.HasKey("Id");

                    b.HasIndex("InstanceId")
                        .IsUnique();

                    b.HasIndex("LastHeartbeatUtc");

                    b.ToTable("WorkerLeases");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("RoleId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider");

                    b.Property<string>("ProviderKey");

                    b.Property<string>("ProviderDisplayName");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("LoginProvider");

                    b.Property<string>("Name");

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Mail2SNMP.Models.Entities.DeadLetterEntry", b =>
                {
                    b.HasOne("Mail2SNMP.Models.Entities.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mail2SNMP.Models.Entities.SnmpTarget", "SnmpTarget")
                        .WithMany()
                        .HasForeignKey("SnmpTargetId");

                    b.HasOne("Mail2SNMP.Models.Entities.WebhookTarget", "WebhookTarget")
                        .WithMany()
                        .HasForeignKey("WebhookTargetId");

                    b.Navigation("Event");

                    b.Navigation("SnmpTarget");

                    b.Navigation("WebhookTarget");
                });

            modelBuilder.Entity("Mail2SNMP.Models.Entities.Event", b =>
                {
                    b.HasOne("Mail2SNMP.Models.Entities.Job", "Job")
                        .WithMany("Events")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("Mail2SNMP.Models.Entities.EventDedup", b =>
                {
                    b.HasOne("Mail2SNMP.Models.Entities.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mail2SNMP.Models.Entities.Job", "Job")
                        .WithMany()
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("Job");
                });

            modelBuilder.Entity("Mail2SNMP.Models.Entities.Job", b =>
                {
                    b.HasOne("Mail2SNMP.Models.Entities.Mailbox", "Mailbox")
                        .WithMany("Jobs")
                        .HasForeignKey("MailboxId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mail2SNMP.Models.Entities.Rule", "Rule")
                        .WithMany("Jobs")
                        .HasForeignKey("RuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mailbox");

                    b.Navigation("Rule");
                });

            modelBuilder.Entity("Mail2SNMP.Models.Entities.JobSnmpTarget", b =>
                {
                    b.HasOne("Mail2SNMP.Models.Entities.Job", "Job")
                        .WithMany("JobSnmpTargets")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mail2SNMP.Models.Entities.SnmpTarget", "SnmpTarget")
                        .WithMany()
                        .HasForeignKey("SnmpTargetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Job");

                    b.Navigation("SnmpTarget");
                });

            modelBuilder.Entity("Mail2SNMP.Models.Entities.JobWebhookTarget", b =>
                {
                    b.HasOne("Mail2SNMP.Models.Entities.Job", "Job")
                        .WithMany("JobWebhookTargets")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mail2SNMP.Models.Entities.WebhookTarget", "WebhookTarget")
                        .WithMany()
                        .HasForeignKey("WebhookTargetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Job");

                    b.Navigation("WebhookTarget");
                });

            modelBuilder.Entity("Mail2SNMP.Models.Entities.ProcessedMail", b =>
                {
                    b.HasOne("Mail2SNMP.Models.Entities.Mailbox", "Mailbox")
                        .WithMany()
                        .HasForeignKey("MailboxId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mailbox");
                });

            modelBuilder.Entity("Mail2SNMP.Models.Entities.Schedule", b =>
                {
                    b.HasOne("Mail2SNMP.Models.Entities.Job", "Job")
                        .WithMany("Schedules")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Mail2SNMP.Models.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Mail2SNMP.Models.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mail2SNMP.Models.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Mail2SNMP.Models.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Mail2SNMP.Models.Entities.Job", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("JobSnmpTargets");

                    b.Navigation("JobWebhookTargets");

                    b.Navigation("Schedules");
                });

            modelBuilder.Entity("Mail2SNMP.Models.Entities.Mailbox", b =>
                {
                    b.Navigation("Jobs");
                });

            modelBuilder.Entity("Mail2SNMP.Models.Entities.Rule", b =>
                {
                    b.Navigation("Jobs");
                });
#pragma warning restore 612, 618
        }
    }
}
